<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
      <ProjectReference Include="..\dataaccess\dataaccess.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
    <Folder Include="Etc\" />
    <Folder Include="Models\" />
    <Folder Include="Services\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
