<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>dataaccess</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.1" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.1">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="DataSeeder\**" />
        <EmbeddedResource Remove="DataSeeder\**" />
        <None Remove="DataSeeder\**" />
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="Seed\**" />
        <EmbeddedResource Remove="Seed\**" />
        <None Remove="Seed\**" />
    </ItemGroup>

</Project>
