<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

    <ItemGroup>
        <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
        <ProjectReference Include="..\dataaccess\dataaccess.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../api/api.csproj" />
        <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" Version="9.10.0" />
        <PackageReference Include="Testcontainers.PostgreSql" Version="4.9.0" />
        <PackageReference Include="Xunit.DependencyInjection" Version="10.7.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
        <PackageReference Include="xunit.v3" Version="3.0.1" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.0" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
    </ItemGroup>

</Project>
